<a href="https://colab.research.google.com/github/monindew/Pytorch_Study/blob/main/20240816.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import torch
import torch.nn as nn

class LinearRegressionModel(nn.Module):
  def __init__(self, input_dim, output_dim):
    super().__init__()
    self.linear = nn.Linear(in_features=input_dim, out_features=output_dim)
    # self.activation = nn.Sigmoid()
    # self.activation = nn.ReLU()
    self.activation = nn.LeakyReLU(0.1)

  def forward(self, x):
    return self.activation(self.linear(x))

In [16]:
x = torch.ones(4)
y = torch.zeros(3)
model = LinearRegressionModel(4, 3)
loss_function = nn.MSELoss()

In [17]:
learning_rate = 0.01
nb_epochs = 1000
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(nb_epochs + 1):
  y_pred = model(x)
  loss = loss_function(y_pred, y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

In [18]:
print(loss)
for param in model.parameters():
  print(param)

tensor(0.0005, grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[ 0.1208,  0.4079, -0.4643, -0.4538],
        [-0.0741,  0.0822, -0.0110, -0.2924],
        [-0.1870,  0.5035, -0.3656, -0.1767]], requires_grad=True)
Parameter containing:
tensor([ 0.3894,  0.2954, -0.1669], requires_grad=True)


In [23]:
class LinearRegressionModel(nn.Module):
  def __init__(self, input_dim, output_dim):
    super().__init__()
    self.linear1 = nn.Linear(input_dim, 10)
    self.linear2 = nn.Linear(10, 10)
    self.linear3 = nn.Linear(10, 10)
    self.linear4 = nn.Linear(10, output_dim)
    self.activation = nn.LeakyReLU(0.1)

  def forward(self, x):
    hidden = self.activation(self.linear1(x))
    hidden = self.activation(self.linear2(hidden))
    hidden = self.activation(self.linear3(hidden))
    y = self.linear4(hidden)
    return y

In [24]:
x = torch.ones(4)
y = torch.zeros(3)
model = LinearRegressionModel(4, 3)
loss_function = nn.MSELoss()

In [25]:
learning_rate = 0.01
nb_epochs = 1000
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(nb_epochs + 1):
  y_pred = model(x)
  loss = loss_function(y_pred, y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

In [26]:
print(loss)
for param in model.parameters():
  print(param)

tensor(6.5640e-08, grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[-0.1103,  0.3809,  0.2399,  0.0599],
        [ 0.3297,  0.1833,  0.1622,  0.0975],
        [-0.4920, -0.1018,  0.2924, -0.3750],
        [ 0.0945, -0.1224,  0.3234, -0.4144],
        [-0.1245,  0.0801, -0.0578,  0.3443],
        [ 0.1985,  0.2120,  0.4401,  0.1760],
        [-0.1715, -0.4869,  0.3893, -0.4574],
        [ 0.2987, -0.4505,  0.3837,  0.1097],
        [-0.2493,  0.2672,  0.0092,  0.4059],
        [-0.3651,  0.3317,  0.3448,  0.3477]], requires_grad=True)
Parameter containing:
tensor([ 0.0609,  0.2570, -0.4667, -0.3494,  0.0826,  0.0123,  0.0736,  0.0335,
         0.2990,  0.3014], requires_grad=True)
Parameter containing:
tensor([[ 0.1116, -0.1165, -0.2237,  0.1882, -0.1025, -0.1524,  0.2193,  0.1979,
         -0.2022,  0.0684],
        [-0.1293,  0.0976,  0.2462,  0.1527, -0.2292,  0.1244,  0.0277, -0.2433,
          0.1581, -0.0670],
        [-0.1676,  0.2462, -0.0030, -0.0803,  0.0476, -0.1608

In [29]:
x = torch.ones(4)
y = torch.zeros(3)

input_dim = x.size(0)
output_dim = y.size(0)

model = nn.Sequential(
    nn.Linear(input_dim, 10),
    nn.LeakyReLU(0.1),
    nn.Linear(10, 10),
    nn.LeakyReLU(0.1),
    nn.Linear(10, 10),
    nn.LeakyReLU(0.1),
    nn.Linear(10, output_dim)
)

In [30]:
loss_function = nn.MSELoss()
learning_rate = 0.01
nb_epochs = 1000
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(nb_epochs + 1):
  y_pred = model(x)
  loss = loss_function(y_pred, y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

print(loss)
for param in model.parameters():
  print(param)

tensor(4.0646e-12, grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[ 0.4849,  0.0935, -0.4539,  0.2831],
        [ 0.0115, -0.1284,  0.0575,  0.4692],
        [-0.1513, -0.3929, -0.4989,  0.0743],
        [ 0.1420,  0.1416, -0.4146,  0.4786],
        [-0.4399, -0.0709,  0.2614, -0.0296],
        [-0.3673,  0.0157, -0.2803,  0.4531],
        [ 0.0835, -0.3393,  0.2940,  0.2163],
        [-0.0170,  0.4646, -0.4159,  0.2622],
        [ 0.4497,  0.1653,  0.3399,  0.2634],
        [-0.2929,  0.0620,  0.4991,  0.3065]], requires_grad=True)
Parameter containing:
tensor([-0.0854,  0.0100,  0.1076, -0.1957,  0.0603, -0.4840, -0.3335,  0.4280,
         0.0439, -0.2083], requires_grad=True)
Parameter containing:
tensor([[ 0.1932,  0.0684,  0.0771, -0.2920,  0.0407, -0.1936, -0.1488, -0.0957,
         -0.1753,  0.1425],
        [ 0.2322, -0.1521, -0.1070, -0.2965, -0.1814, -0.2728, -0.1379,  0.0555,
         -0.0130,  0.2487],
        [-0.2008, -0.1087,  0.2321, -0.3160,  0.0235, -0.2737