<a href="https://colab.research.google.com/github/monindew/Pytorch_Study/blob/main/20240807_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

data1 = torch.DoubleTensor([[1, 2, 3], [4, 5, 6]])
print(data1, data1.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64) torch.Size([2, 3])


In [2]:
data1 = data1.reshape(3, 2)
print(data1, data1.shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64) torch.Size([3, 2])


In [3]:
data1 = data1.reshape(2, -1)
print(data1, data1.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64) torch.Size([2, 3])


In [4]:
data1 = torch.DoubleTensor([
    [[1, 2, 3],
     [4, 5, 6]],
    [[7, 8, 9],
     [10, 11, 12]]
])
print(data1.shape, "높이(k):", data1.size(0), "너비(n):", data1.size(1), "깊이(m):", data1.size(2))

torch.Size([2, 2, 3]) 높이(k): 2 너비(n): 2 깊이(m): 3


In [5]:
data1 = data1.view(2, -1)
print(data1, data1.shape)

data1 = data1.view(-1, 3)
print(data1, data1.shape)

data1 = data1.view(3, 2, -1)
print(data1, data1.shape)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]], dtype=torch.float64) torch.Size([2, 6])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]], dtype=torch.float64) torch.Size([4, 3])
tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]], dtype=torch.float64) torch.Size([3, 2, 2])


In [6]:
data1.squeeze()

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]], dtype=torch.float64)

In [7]:
data1 = torch.FloatTensor([[1], [2], [3]])
data2 = data1.squeeze()
print(data1, data1.dim(), data1.shape)
print(data2, data2.dim(), data2.shape)

tensor([[1.],
        [2.],
        [3.]]) 2 torch.Size([3, 1])
tensor([1., 2., 3.]) 1 torch.Size([3])


In [8]:
data1 = torch.FloatTensor([ [1, 2, 3], [4, 5, 6] ])
print(data1, data1.dim(), data1.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]]) 2 torch.Size([2, 3])


In [9]:
data2 = data1.unsqueeze(0)
data3 = data1.unsqueeze(1)
print(data2, data2.dim(), data2.shape)
print(data3, data3.dim(), data3.shape)

tensor([[[1., 2., 3.],
         [4., 5., 6.]]]) 3 torch.Size([1, 2, 3])
tensor([[[1., 2., 3.]],

        [[4., 5., 6.]]]) 3 torch.Size([2, 1, 3])


In [10]:
data1 = torch.zeros(2, dtype=torch.float)
data2 = torch.ones(2, 4, dtype=torch.double)
data3 = torch.rand(2, 2, 3, dtype=torch.half)
print(data1.dtype, data2.dtype, data3.dtype)

data1 = data1.type(torch.float32)
data2 = data2.type(torch.int)
data3 = data3.type(torch.double)
print(data1.dtype, data2.dtype, data3.dtype)

torch.float32 torch.float64 torch.float16
torch.float32 torch.int32 torch.float64


In [11]:
print(data2)
data2 = data2.T
print(data2)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int32)


In [12]:
import numpy as np
data1 = np.array([[1, 2], [3, 4]])
print(data1, type(data1))
data2 = torch.from_numpy(data1)
print(data2, type(data2))
data3 = data2.numpy()
print(data3, type(data3))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>
[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [13]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [14]:
torch.arange(1, 5)

tensor([1, 2, 3, 4])

In [15]:
torch.arange(1, 5, 2)

tensor([1, 3])

In [16]:
torch.linspace(1, 5, 4)

tensor([1.0000, 2.3333, 3.6667, 5.0000])

In [17]:
torch.linspace(1, 5, 10)

tensor([1.0000, 1.4444, 1.8889, 2.3333, 2.7778, 3.2222, 3.6667, 4.1111, 4.5556,
        5.0000])

In [20]:
data1 = torch.full((3, 3), 2)
data2 = torch.full((3, 3), 1)
print(data1 + data2)
print(data1 - data2)
print(data1 * data2)
print(data1 / data2)

tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [18]:
data1 = torch.full((3, 2), 2)
data2 = torch.full((2, 3), 1)
torch.matmul(data1, data2)

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])

In [21]:
data1 = torch.FloatTensor([ [1], [2], [3]])
data2 = torch.FloatTensor([1, 1, 1])
data3 = data1 + data2
print(data1.shape, data2.shape, data3.shape)
print(data3)

torch.Size([3, 1]) torch.Size([3]) torch.Size([3, 3])
tensor([[2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]])


In [22]:
data1 = torch.FloatTensor(10, 20, 4)
data2 = torch.FloatTensor(20, 4)
data3 = data1 + data2
print(data1.shape, data2.shape, data3.shape)

torch.Size([10, 20, 4]) torch.Size([20, 4]) torch.Size([10, 20, 4])


In [23]:
data1 = torch.FloatTensor(10, 20, 4)
data2 = torch.FloatTensor(20, 4)
data3 = data1 + data2
print(data1.shape, data2.shape, data3.shape)

torch.Size([10, 20, 4]) torch.Size([20, 4]) torch.Size([10, 20, 4])


In [24]:
data1 = torch.FloatTensor(5)
data2 = torch.FloatTensor(10, 10, 1)
data3 = data1 + data2
print(data1.shape, data2.shape, data3.shape)

torch.Size([5]) torch.Size([10, 10, 1]) torch.Size([10, 10, 5])


In [25]:
data3 = torch.FloatTensor([ [1, 2, 3], [4, 5, 6]])
print(data3)
print(data3[1, 1])
print(data3[:, 1])
print(data3[:, :])
print(data3[:1, :2])

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor(5.)
tensor([2., 5.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2.]])


In [30]:
data1 = torch.FloatTensor([[1, 2, 3], [5, 5, 5]])
data2 = data1 > 3
print(data2)
print(data1[data2])
print(data1[(data1>3) & (data1 < 6)])

tensor([[False, False, False],
        [ True,  True,  True]])
tensor([5., 5., 5.])
tensor([5., 5., 5.])


In [31]:
data1 = torch.randn(4,3)
data1

tensor([[-0.6773, -1.9328,  0.2623],
        [-0.0669, -0.0459, -0.8913],
        [ 0.7378,  0.1086,  0.1719],
        [ 1.0020, -1.1846,  0.0770]])

In [34]:
print(data1[[1, 2, 0]])
print(data1[ [1, -1]])

tensor([[-0.0669, -0.0459, -0.8913],
        [ 0.7378,  0.1086,  0.1719],
        [-0.6773, -1.9328,  0.2623]])
tensor([[-0.0669, -0.0459, -0.8913],
        [ 1.0020, -1.1846,  0.0770]])


In [35]:
print(data1[[1,2]][:, [0,2]])
print(data1[[1,-1]][:, [0]])

tensor([[-0.0669, -0.8913],
        [ 0.7378,  0.1719]])
tensor([[-0.0669],
        [ 1.0020]])


In [36]:
data1 = torch.FloatTensor([ [1, 2, 3], [4, 5, 6]])
print(data1)
data2 = data1[:2, :2]
print(data2)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2.],
        [4., 5.]])


In [37]:
data2[1, 1] = 4
print(data2)
print(data1)

tensor([[1., 2.],
        [4., 4.]])
tensor([[1., 2., 3.],
        [4., 4., 6.]])


In [38]:
data1 = torch.FloatTensor([ [1, 2, 3], [4, 5, 6]])
print(data1)
data2 = data1[:2, :2].clone().detach()
print(data2)
data2[1, 1] = 4
print(data2)
print(data1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2.],
        [4., 5.]])
tensor([[1., 2.],
        [4., 4.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [39]:
data1 = torch.FloatTensor([7, 2, 0, 4, 1])
index = torch.where(data1 < 3)
print(index)
print(data1[index])

(tensor([1, 2, 4]),)
tensor([2., 0., 1.])


In [40]:
print(data1)
data2 = torch.where(data1 < 3, -1, 1)
print(data2)

tensor([7., 2., 0., 4., 1.])
tensor([ 1, -1, -1,  1, -1])


In [41]:
data1 = torch.FloatTensor([ [1, 2, 3], [4, 5, 6]])
data2 = torch.where(data1 < 3, -1, 1)
print(data2)

tensor([[-1, -1,  1],
        [ 1,  1,  1]])


In [42]:
data1 = torch.FloatTensor([ [1, 2, 3], [4, 5, 6]])
print(data1.min())
print(data1.max())
print(data1.sum())
print(data1.mean())
print(data1.var())
print(data1.std())
print(data1.argmin())
print(data1.argmax())

tensor(1.)
tensor(6.)
tensor(21.)
tensor(3.5000)
tensor(3.5000)
tensor(1.8708)
tensor(0)
tensor(5)


In [43]:
data1 = torch.linspace(1, 5, 4)
print(data1)
torch.save(data1, "mydata1.pt")

tensor([1.0000, 2.3333, 3.6667, 5.0000])


In [44]:
data2 = torch.load("mydata1.pt")
print(data2)

tensor([1.0000, 2.3333, 3.6667, 5.0000])


In [46]:
data1 = torch.linspace(1, 5, 4)
data2 = torch.linspace(1, 10, 4)
data3 = torch.linspace(1, 100, 4)
print(data1)
print(data2)
print(data3)
datas = {'data1': data1, 'data2': data2, 'data3': data3}
torch.save(datas, "mydata1.pt")

tensor([1.0000, 2.3333, 3.6667, 5.0000])
tensor([ 1.,  4.,  7., 10.])
tensor([  1.,  34.,  67., 100.])


In [47]:
datas = torch.load('mydata1.pt')
print(datas['data1'])
print(datas['data2'])
print(datas['data3'])

tensor([1.0000, 2.3333, 3.6667, 5.0000])
tensor([ 1.,  4.,  7., 10.])
tensor([  1.,  34.,  67., 100.])
