<a href="https://colab.research.google.com/github/monindew/Pytorch_Study/blob/main/20240811.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn.functional as F

x = torch.ones(4)
y = torch.zeros(3)
W = torch.rand(4, 3, requires_grad=True)
b = torch.rand(3, requires_grad=True)

In [2]:
learning_rate = 0.01
optimizer = torch.optim.SGD([W, b], lr=learning_rate)

In [3]:
nb_epochs = 300
for epoch in range(nb_epochs + 1):
  z = torch.matmul(x, W) + b
  loss = F.mse_loss(z, y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print(epoch, nb_epochs, W, b, loss)

0 300 tensor([[0.9194, 0.2120, 0.7137],
        [0.2750, 0.1550, 0.8223],
        [0.8455, 0.7684, 0.6377],
        [0.7705, 0.2008, 0.2764]], requires_grad=True) tensor([0.7097, 0.2905, 0.0281], requires_grad=True) tensor(7.5551, grad_fn=<MseLossBackward0>)
100 300 tensor([[ 0.2391, -0.1024,  0.2347],
        [-0.4053, -0.1594,  0.3434],
        [ 0.1652,  0.4540,  0.1588],
        [ 0.0902, -0.1136, -0.2025]], requires_grad=True) tensor([ 0.0294, -0.0238, -0.4508], requires_grad=True) tensor(0.0086, grad_fn=<MseLossBackward0>)
200 300 tensor([[ 0.2161, -0.1130,  0.2186],
        [-0.4282, -0.1700,  0.3272],
        [ 0.1423,  0.4434,  0.1426],
        [ 0.0672, -0.1242, -0.2187]], requires_grad=True) tensor([ 0.0065, -0.0344, -0.4670], requires_grad=True) tensor(9.7488e-06, grad_fn=<MseLossBackward0>)
300 300 tensor([[ 0.2154, -0.1134,  0.2180],
        [-0.4290, -0.1703,  0.3267],
        [ 0.1415,  0.4431,  0.1421],
        [ 0.0665, -0.1245, -0.2192]], requires_grad=True) tensor([

In [4]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class LinearRegressionModel(nn.Module):
  def __init__(self, input_dim, output_dim):
    super().__init__()
    self.linear = nn.Linear(input_dim, output_dim)

  def forward(self, x):
    return self.linear(x)

model = LinearRegressionModel(4, 3)

In [5]:
x = torch.ones(4)
y = torch.zeros(3)

learning_rate = 0.01
nb_epochs = 1000
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(nb_epochs + 1):
  pred = model(x)
  loss = F.mse_loss(pred, y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

In [6]:
print(loss)
for param in model.parameters():
  print(param)

tensor(2.1015e-13, grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[ 0.5084, -0.1142, -0.1194, -0.3512],
        [ 0.0881, -0.0179,  0.2796, -0.0963],
        [ 0.2373,  0.2859, -0.1092, -0.1752]], requires_grad=True)
Parameter containing:
tensor([ 0.0764, -0.2534, -0.2386], requires_grad=True)


In [7]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes
diabetes_data = load_diabetes()

print(diabetes_data.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, total serum cholesterol
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, total cholesterol / HDL
      - s5      ltg, possibly log of serum triglycerides level
      - s6      glu, blood sugar level

Note: Each of these 1

In [8]:
x = torch.from_numpy(np.array(diabetes_data.data[:, :-1], dtype=np.float32))
y = torch.from_numpy(np.array(diabetes_data.data[:, [-1]], dtype=np.float32))

In [9]:
print("shape of x is :", x.shape)
print("shape of y is :", y.shape)

shape of x is : torch.Size([442, 9])
shape of y is : torch.Size([442, 1])


In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class LinearRegressionModel(nn.Module):
  def __init__(self, input_dim, output_dim):
    super().__init__()
    self.linear = nn.Linear(input_dim, output_dim)

  def forward(self, x):
    return self.linear(x)

In [11]:
model = LinearRegressionModel(x.size(1), y.size(1))

In [12]:
learning_rate = 0.01
nb_epochs = 10000
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [13]:
for epoch in range(nb_epochs + 1):
  y_pred = model(x)
  loss = F.mse_loss(y_pred, y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

In [14]:
print(loss)
for param in model.parameters():
  print(param)

tensor(0.0017, grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[ 0.0060,  0.0158,  0.0876,  0.2591, -0.1300,  0.2576, -0.2437, -0.0738,
          0.1373]], requires_grad=True)
Parameter containing:
tensor([2.3417e-10], requires_grad=True)


In [15]:
df = pd.DataFrame(torch.cat([y, y_pred], dim=1).detach_().numpy(), columns=["y", "y_pred"])

In [16]:
import plotly.graph_objects as go
import plotly.offline as pyo
pyo.init_notebook_mode(connected=True)

fig = go.Figure()

fig.add_trace(go.Scatter(x=df.index, y=df["y"], mode="markers", name="y"))
fig.add_trace(go.Scatter(x=df.index, y=df["y_pred"], mode="markers", name="y_pred"))

fig.update_layout(yaxis_range=[-0.5, 0.5])
fig.show(renderer="colab")