<a href="https://colab.research.google.com/github/monindew/Pytorch_Study/blob/main/20240807.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

torch.__version__

'2.3.1+cu121'

In [2]:
import numpy as np
data1 = np.array(10)

In [4]:
print(data1)
print(data1.ndim)
print(data1.shape)

10
0
()


In [5]:
data1 = torch.FloatTensor([1, 2])
print(data1, data1.dim(), data1.shape)

tensor([1., 2.]) 1 torch.Size([2])


In [6]:
data2 = torch.FloatTensor(3)
print(data2, data2.dim(), data2.shape)

tensor([-2.7329e+18,  3.2877e-41, -2.3301e-12]) 1 torch.Size([3])


In [7]:
data3 = torch.FloatTensor(3, 2)
print(data3, data3.dim(), data3.shape)

tensor([[2.9949e+22, 3.2873e-41],
        [3.0726e+22, 3.2873e-41],
        [1.1210e-43, 0.0000e+00]]) 2 torch.Size([3, 2])


In [8]:
data4 = torch.FloatTensor([ [1, 2], [3, 4], [5, 6]])
print(data4, data4.dim(), data4.shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) 2 torch.Size([3, 2])


In [9]:
data5 = torch.FloatTensor(3, 2, 1)
print(data5, data5.dim(), data5.shape)

tensor([[[-8.9576e+18],
         [ 3.2877e-41]],

        [[ 0.0000e+00],
         [ 1.1755e-38]],

        [[ 3.1819e+19],
         [ 3.2873e-41]]]) 3 torch.Size([3, 2, 1])


In [10]:
data6 = torch.FloatTensor([[ [1], [2] ], [[3], [4]], [[5], [6]]])
print(data6, data6.dim(), data6.shape)

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]],

        [[5.],
         [6.]]]) 3 torch.Size([3, 2, 1])


In [12]:
data7 = torch.FloatTensor([ [1], [2], [3] ])
print(data7, data7.dim(), data7.shape)

tensor([[1.],
        [2.],
        [3.]]) 2 torch.Size([3, 1])


In [13]:
data8 = torch.FloatTensor([ [1, 2, 3] ])
print(data8, data8.dim(), data8.shape)

tensor([[1., 2., 3.]]) 2 torch.Size([1, 3])


In [15]:
data1 = torch.zeros(2, dtype=torch.float)
data2 = torch.ones(2, 2, dtype=torch.double)
data3 = torch.rand(2, 2, 3, dtype=torch.half)
data4 = torch.randn(2, 2, 3, 4)
data5 = torch.full((2,4), 10)

print(data1.shape, data2.shape, data3.shape, data4.shape, data5.shape, data5.dtype)

torch.Size([2]) torch.Size([2, 2]) torch.Size([2, 2, 3]) torch.Size([2, 2, 3, 4]) torch.Size([2, 4]) torch.int64


In [16]:
print(data1.ndim, data2.ndim, data3.ndim, data4.ndim, data5.ndim)
print(data1.dim(), data2.dim(), data3.dim(), data4.dim(), data5.dim())

1 2 3 4 2
1 2 3 4 2


In [17]:
print(data1.dtype, data2.dtype, data3.dtype, data4.dtype, data5.dtype)

torch.float32 torch.float64 torch.float16 torch.float32 torch.int64


In [18]:
print(data1.size(), data2.size(), data3.size(), data4.size(), data5.size())

torch.Size([2]) torch.Size([2, 2]) torch.Size([2, 2, 3]) torch.Size([2, 2, 3, 4]) torch.Size([2, 4])


In [19]:
data6 = torch.FloatTensor([ [1,2], [3,4] ])
data7 = torch.DoubleTensor([ [1,2,3], [4,5,6]])
data8 = torch.LongTensor([[1,2,3], [4,5,6], [7,8,9]])

In [20]:
data9 = torch.FloatTensor(2, 3, 5)
data10 = torch.DoubleTensor(3, 3, 2, 4)
data11 = torch.LongTensor(4, 4)

In [21]:
data11

tensor([[3688791379240040994, 7378080558593631799, 3689632707852263733,
         7005741983074498866],
        [3688834449525847093, 8317341608397911352, 4189022137156394855,
         7162254423478575648],
        [2484135899465670516, 7958535038077902892, 8440344085702995297,
         2478507435169572211],
        [7598543875864666156, 4050743911652683375, 3831827917486633777,
         3847823621153449572]])

In [22]:
data12 = torch.full_like(data5, 20)

In [23]:
print(data5)
print(data12)

tensor([[10, 10, 10, 10],
        [10, 10, 10, 10]])
tensor([[20, 20, 20, 20],
        [20, 20, 20, 20]])
