<a href="https://colab.research.google.com/github/monindew/Pytorch_Study/blob/main/20240816_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

data1 = torch.randn(3, 4)
print(data1)
indices = torch.tensor([1, 2])
print(indices)
print(torch.index_select(data1, 0, indices))
print(torch.index_select(data1, 1, indices))

tensor([[ 0.7807, -0.3112,  0.0602,  0.4125],
        [ 0.1432, -0.7276,  0.4472, -0.8463],
        [-0.3554,  1.2097, -0.1917,  1.4281]])
tensor([1, 2])
tensor([[ 0.1432, -0.7276,  0.4472, -0.8463],
        [-0.3554,  1.2097, -0.1917,  1.4281]])
tensor([[-0.3112,  0.0602],
        [-0.7276,  0.4472],
        [ 1.2097, -0.1917]])


In [5]:
x = torch.ones(5000, 10)
y = torch.zeros(5000, 1)
learning_rate = 0.01
nb_epochs = 1000
minibatch_size = 256

In [9]:
input_dim = x.size(-1)
output_dim = y.size(-1)

model = nn.Sequential(
    nn.Linear(input_dim, 10),
    nn.LeakyReLU(0.1),
    nn.Linear(10, 8),
    nn.LeakyReLU(0.1),
    nn.Linear(8, 6),
    nn.LeakyReLU(0.1),
    nn.Linear(6, output_dim)
)

loss_function = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [14]:
indices = torch.randperm(x.size(0))
print(indices)
x_batch_list = torch.index_select(x, 0, index=indices)
y_batch_list = torch.index_select(y, 0, index=indices)
x_batch_list = x_batch_list.split(minibatch_size, dim=0)
y_batch_list = y_batch_list.split(minibatch_size, dim=0)
print(len(x_batch_list), len(y_batch_list))

tensor([1405, 4476, 1500,  ..., 4799,  868, 4203])
20 20


In [15]:
x_batch_list[0]

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [16]:
for index in range(nb_epochs):
  indices = torch.randperm(x.size(0))
  x_batch_list = torch.index_select(x, 0, index=indices)
  y_batch_list = torch.index_select(y, 0, index=indices)
  x_batch_list = x_batch_list.split(minibatch_size, dim=0)
  y_batch_list = y_batch_list.split(minibatch_size, dim=0)

  for x_minibatch, y_minibatch in zip(x_batch_list, y_batch_list):
    y_minibatch_pred = model(x_minibatch)
    loss = loss_function(y_minibatch_pred, y_minibatch)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print(loss)
for param in model.parameters():
  print(param)


tensor(2.7200e-15, grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[-0.0715,  0.1495, -0.0620,  0.2064, -0.1906,  0.2236, -0.0444,  0.0041,
          0.0681, -0.2047],
        [-0.0382,  0.2451,  0.2908, -0.2726,  0.3063, -0.0416, -0.1575, -0.0632,
         -0.3150,  0.1104],
        [-0.2896, -0.0153, -0.2063, -0.1356,  0.2928, -0.1415,  0.1258, -0.0429,
          0.3079,  0.2389],
        [ 0.2156, -0.1528, -0.2096,  0.0393, -0.1435,  0.2113,  0.1049,  0.1198,
          0.1269, -0.0302],
        [-0.1390,  0.0352,  0.2939, -0.1429, -0.1357, -0.2353, -0.1256, -0.1658,
         -0.2420,  0.2477],
        [ 0.2740, -0.0874, -0.0027,  0.3135, -0.1471,  0.0343, -0.2327, -0.1902,
         -0.1650,  0.2325],
        [-0.2210, -0.1358, -0.0356, -0.0188, -0.1438,  0.2951,  0.3014, -0.2974,
          0.1871, -0.0410],
        [-0.2673, -0.3015, -0.2341, -0.1557, -0.0394, -0.2808, -0.0226, -0.1529,
          0.0394, -0.1901],
        [ 0.2795, -0.2744,  0.1742, -0.2238,  0.1443, -0.30